export default {
    WHITE: "#FFFFFF",
    BLACK: "#000000",
    THEME: "#3B92ED",
    INPUTBOX_DEACTIVE_BORDER_COLOR: "#CCCCCC",
    BUTTON_GRADIENT_ONE: "#3B92ED",
    BUTTON_GRADIENT_TWO: "#3B92ED",
    PLACEHOLDER: "#B0B0B0"
}